namespace tiles.util {
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const arrow15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const door15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const object15 = image.ofBuffer(hex``);
}
